name: Run Checker VPN

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run main script
        run: python3 main.py

      - name: Commit subs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Безопасная проверка: создаем пустую папку, если скрипт её не создал, чтобы Git не падал
          mkdir -p subs
          touch subs/.gitkeep
          
          git add subs/
          
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update validated subs"
            git push origin main
          fi
