name: Update VPN Subs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run main script
        run: |
          python3 main.py

      - name: Commit subs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add subs/*.txt

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update validated subs"
            git push
          fi
